### ISSUE TITLE
Remove Installation of applications in Makefile (README or Requirements)

### ISSUE THREAD

**Issue by alexandref75** [veracruz-project/veracruz-examples#5]
The makefile install applications on user system from the Makefile, this should be on the README or requirements.  

##########################################################
yolo_detection:
	if [ "$(OS)" = "macos" ]; then \
		brew install imagemagick ghostscript; \
	elif [ "$(OS)" = "linux" ]; then \
		sudo apt install imagemagick; \
	fi

**Comment by gbryant-arm** [comment]
For security reasons?
As as sidenote this issue comes from the deep learning server example.

**Comment by alexandref75** [comment]
Three main reasons: 
1. You are technically trying to install them every time you make yolo_detection. You can get away from that by testing if the tool exists and fail the make with a request to install the referenced tool.
2. Silent install of tools. (You can put a phony target called install_requirements). 
3. It only works on ubuntu or debian. Other distributions will not have apt so the command will fail.

**Comment by alexandref75** [comment]
A few other reasons:
4. The list is not complete, are you checking compilers and other tools?

**Comment by gbryant-arm** [comment]
The Makefile installs wasi sdk, the WASM toochain. That shouldn't be here either.

**Comment by alexandref75** [comment]
So that should be moved to the same place you moved the other installations.

**Comment by gbryant-arm** [comment]
Comments addressed, closing issue
